---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: debian-7.1
  driver_config:
    box: debian
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box

suites:
- name: unimrcp
  run_list: ['recipe[unimrcp]']
  attributes: {
    unimrcp: {}
  }
- name: flite
  run_list: ['recipe[unimrcp]']
  attributes: {
    unimrcp: {
      install_flite: true
    }
  }
- name: pocketsphinx
  run_list: ['recipe[unimrcp]']
  attributes: {
    unimrcp: {
      install_pocketsphinx: true
    }
  }
